### ISSUE TITLE
BitDefender started to have an issue with the new version

### ISSUE THREAD

**Issue by azur3wrath** [IceDynamix/reliquary-archiver#50] opened 2024-08-15 21:10 UTC
Im having a permanent hit on the new executable with Gen:Variant.Tedy.607416 by BitDefender.
Do you know by any chance if its a false positive?

**Comment by Mimo-Bn** [comment] 2024-08-16 12:19
i'm having a similar issue with my norton flagging it

**Comment by IceDynamix** [comment] 2024-08-22 00:20
duplicate of https://github.com/IceDynamix/reliquary-archiver/issues/36

**Closed by IceDynamix** 2024-08-22 00:20 UTC
