### ISSUE TITLE
Wrong Caelus path

### ISSUE THREAD

**Issue by damiananero** [IceDynamix/reliquary-archiver#25] opened 2024-06-07 18:23 UTC
My Caelus is Harmony, but every time he is identified as Hunt and lose all his equipped relics

![изображение](https://github.com/IceDynamix/reliquary-archiver/assets/12477086/fb2c43ce-5170-4600-9c59-1161feba82bd)

**Comment by FaeronGaming** [comment] 2024-06-07 18:28
Duplicate of #16, will be fixed in the next release

**Closed** 2024-06-12 00:22 UTC
