### ISSUE TITLE
Error in init database

### ISSUE THREAD

**Issue by 12345-mcpython** [IceDynamix/reliquary-archiver#13] opened 2024-05-03 12:08 UTC
``` 2024-05-03T12:02:44.209674Z  INFO config_map: reliquary_archiver::export::fribbels: initializing database from online sources, this might take a while...
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Transport(Transport { kind: ConnectionFailed, message: Some("tls connection init failed"), url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("raw.githubusercontent.com")), port: None, path: "/Dimbreath/StarRailData/master/ExcelOutput/AvatarConfig.json", query: None, fragment: None }), source: Some(Custom { kind: InvalidData, error: InvalidCertificate(UnknownIssuer) }) })
Location: src\export\fribbels.rs:300

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Warning: SpanTrace capture is Unsupported.
Ensure that you've setup a tracing-error ErrorLayer and the semver versions are compatible
```

It seems be a network problem. Can you build the mirror of links?

**Comment by Arbitraryfate** [comment] 2024-05-12 08:56
got same error, do you fix it?

**Comment by IceDynamix** [comment] 2024-06-07 02:55
closing for now, since this seems to be a duplicate of #17

**Closed by IceDynamix** 2024-06-07 02:55 UTC
